---
apiVersion: v1
kind: Namespace
metadata:
  name: incepta
  labels:
    name: incepta
    environment: ${ENV}
    managed-by: kustomize
    app.kubernetes.io/name: incepta
    app.kubernetes.io/part-of: incepta-platform
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: platform-team
  annotations:
    # Prometheus monitoring configuration
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/path: "/metrics"
    
    # Environment and resource management annotations
    incepta.io/resource-tier: ${ENV}
    incepta.io/quota-scope: namespace
    incepta.io/monitoring-enabled: "true"
    
    # Resource quotas and limits
    incepta.io/cpu-request: "16"
    incepta.io/cpu-limit: "32"
    incepta.io/memory-request: "32Gi"
    incepta.io/memory-limit: "64Gi"
    
    # Security configurations
    incepta.io/network-policy: "default-deny"
    incepta.io/pod-security-enabled: "true"
    incepta.io/rbac-enabled: "true"
    
    # Monitoring and alerting
    incepta.io/alert-threshold-quota: "85"
    incepta.io/alert-threshold-restarts: "5"
    
    # Environment-specific configurations
    incepta.io/resource-multiplier: "${ENV_MULTIPLIER}"
    incepta.io/high-availability: "${HA_ENABLED}"
    incepta.io/backup-enabled: "${BACKUP_ENABLED}"
    
    # Documentation
    kubernetes.io/description: "Namespace for Incepta platform components with comprehensive resource management, security, and monitoring configurations"

---
# Resource Quota definition for the namespace
apiVersion: v1
kind: ResourceQuota
metadata:
  name: incepta-quota
  namespace: incepta
spec:
  hard:
    # Compute resources
    requests.cpu: "16"
    limits.cpu: "32"
    requests.memory: "32Gi"
    limits.memory: "64Gi"
    
    # Object count limits
    pods: "100"
    services: "50"
    secrets: "100"
    configmaps: "50"
    persistentvolumeclaims: "25"
    services.loadbalancers: "5"
    services.nodeports: "10"

---
# LimitRange definition for default resource constraints
apiVersion: v1
kind: LimitRange
metadata:
  name: incepta-limits
  namespace: incepta
spec:
  limits:
  - type: Container
    default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    max:
      cpu: "4"
      memory: "8Gi"
    min:
      cpu: "50m"
      memory: "64Mi"

---
# NetworkPolicy for default deny-all with explicit allows
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: incepta
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/system: kube-system
    ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP