apiVersion: v1
kind: Secret
metadata:
  name: incepta-secrets
  namespace: default
  labels:
    app: incepta
    component: secrets
  annotations:
    kubernetes.io/created-by: manual
    incepta.io/last-rotated: "2024-01-18T00:00:00Z"  # Example timestamp
    incepta.io/rotation-schedule: varies-by-secret-type
type: Opaque
data:
  # Database Credentials
  # Rotation: 90 days
  DB_USER: <base64_encoded_value>  # PostgreSQL database username
  DB_PASSWORD: <base64_encoded_value>  # PostgreSQL database password (32+ chars)
  DB_SSL_CERT: <base64_encoded_value>  # PostgreSQL SSL certificate
  
  # Authentication Secrets
  # Rotation: 180 days for JWT, varies for OAuth
  JWT_SECRET: <base64_encoded_value>  # 512-bit JWT signing key
  OAUTH_CLIENT_ID: <base64_encoded_value>  # Auth0 OAuth client ID
  OAUTH_CLIENT_SECRET: <base64_encoded_value>  # Auth0 OAuth client secret
  
  # AWS Credentials
  # Rotation: 30 days
  AWS_ACCESS_KEY_ID: <base64_encoded_value>  # AWS access key for S3/KMS
  AWS_SECRET_ACCESS_KEY: <base64_encoded_value>  # AWS secret key for S3/KMS
  
  # Service Credentials
  # Rotation: 90 days
  ELASTICSEARCH_PASSWORD: <base64_encoded_value>  # Elasticsearch service password
  REDIS_PASSWORD: <base64_encoded_value>  # Redis service password

---
# Mount configurations are implemented through Pod/Deployment specs
# Example mount configuration for reference:
#
# spec:
#   containers:
#   - name: api-server
#     volumeMounts:
#     - name: secrets-volume
#       mountPath: /app/secrets
#       readOnly: true
#   volumes:
#   - name: secrets-volume
#     secret:
#       secretName: incepta-secrets
#       defaultMode: 0400
#       items:
#       - key: DB_USER
#         path: db_user
#       - key: DB_PASSWORD
#         path: db_password
#       # ... other secrets as needed